---
- hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm


  tasks:
   - name: Create incident
     servicenow.itsm.incident:
      instance:
       #host: "ansible.servicenow.com"
       #username: "{{ SN_USERNAME }}"
       #password: "{{ SN_PASSWORD }}"
      state: new
      short_description: "{{ ansible_eda.event.body.event.action }}"
      description: |-
       Details: {{ ansible_eda.event.body.message | default("") }}
       Event-ID: {{ ansible_eda.event.body.winlog.event_id | default("") }}
       Event-Outcome: {{ ansible_eda.event.body.event.outcome | default("") }}
     register: new_incident

   - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

   - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"
