---

- name: launching an ec2 instance 2
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: find a subnet id
    ec2_vpc_subnet_info:
      region: us-east-1
    register: subnet_ids

  - name: create a security group
    ec2_group:
      name: example
      description: "security FTW"
      region: us-east-1
      vpc_id: "{{subnet_ids.subnets[0].vpc_id}}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
    register: my_security_group

  - name: launch an ec2 instance
    ec2:
      instance_type: t2.micro
      region: us-east-1
      image: ami-0c41531b8d18cc72b
      group_id: "{{my_security_group.group_id}}"
      key_name: laptop
      instance_tags:
        Name: "{{ instance_name }}"
      wait: yes
      vpc_subnet_id: "{{subnet_ids.subnets[0].id}}"
      assign_public_ip: yes
    register: ec2_instance  
