---
- name: Delete a ressource group 
  hosts: localhost
  connection: local
  gather_facts: false

  tasks: 
    - name: Delete a resource group including resources it contains
      azure_rm_resourcegroup:
        name: "{{ ressource_group }}"
        force: yes
        state: absent
