---
- name: Delete a ressource group 
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID')}}"
    azure_tenant: "{{ lookup('env', 'AZURE_TENANT')}}"
    azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID')}}"
    azure_secret: "{{ lookup('env', 'AZURE_SECRET')}}"

  tasks: 
    - name: Delete a resource group including resources it contains
      azure_rm_resourcegroup:
        name: "{{ ressource_group }}"
#   force_delete_nonempty: yes
        state: absent