---
- name: verifie les maj disponibles pour RHEL
  hosts: all
  tasks: 
    - name: verifie les maj
      dnf: 
        list: updates
        update_cache: true
      register: dnfoutput
    - name: affiche resutat 
      debug: 
        var: dnfoutput
