---
- name: verifie les maj disponibles pour RHEL
  hosts: all
  tasks: 
    - name: verifie les maj
      dnf: 
        list: updates
        update_cache: true
      register: dnfoutput
    - name: liste contractée
      debug:
        msg: "{{ dnfoutput.results | map(attribute='name') | list }}"
    - name: list détaillée 
      debug: 
        var: dnfoutput 
    - name: copy resultat sur host 
      copy: 
        content="{{ dnfoutput }}" dest=/tmp/updates.log
