---
- name: windows server patching
  hosts: all
  tasks:

    - name: Check for missing updates
      win_updates:
        state: searched
        log_path: C:\ansible_wu.txt
      register: update_results

    - name: report update results
      debug:
        var: update_results
