---
- name: windows server patching
  hosts: all
  tasks:

    - name: Check for missing updates
      win_updates:
        state: searched
        log_path: C:\ansible_wu.txt
      register: available_updates

     - debug:
         msg: |
           {{ inventory_hostname }} has {{ available_updates.found_update_count }} updates available.
           {% for key, value in available_updates.updates.iteritems() %}
           - KB: {{ value.title }}
           {% endfor %}
