---
- name: verifie les maj disponibles pour RHEL
  hosts: all
  tasks: 
    - name: verifie les maj
      dnf: 
        list: updates
        update_cache: true
      register: dnfoutput
    - debug:
        msg: "{{ dnfoutput.results | map(attribute='name') | list }}"
