---
- name: Remove vm in Amazon
  hosts: localhost
  connection: local
  gather_facts: false

  tasks: 
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: us-east-1
        name: "{{ instance_name }}" 
