- name: Delete an instance 
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    project_id: project-id

  tasks:

   - name: Terminate instances
     gce:
         instance_names: "{{ instance_name }}"
         state: absent
