- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    project_id: project-id
    machine_type: n1-standard-1
    image: rhel-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: demo
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
