- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    project_id: project-id
    machine_type: e2-medium
    image: rhel-9-v20220822

  tasks:

   - name: Launch instances
     gce:
         instance_names: "{{ instance_name }}"
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
