---
- name: installe et configure IIS
  hosts: all
  gather_facts: no
  vars:
    port: 8080
  tasks:
    - name: create a folder to store IIS site
      win_file:
        path: C:\ansible
        state: directory


    - name: install the IIS features
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: no
        include_management_tools: no

    - name: w3svc reset
      win_service:
        name: w3svc
        state: started
