
---
- name: internet services
  hosts: serverb.lab.example.com
  become: yes
  tasks:
  - block:
    - name: latest httpd version installed
      yum:
        name: httpd
        state: latest
    - name: latest firewalld version installed
      yum:
        name: firewalld
        state: latest
    - name: latest mariadb-server version installed
      yum:
        name: mariadb-server
        state: latest
    - name: latest php version installed
      yum:
        name: php
        state: latest
    - name: latest php-mysql version installed
      yum:
         name: php-mysql
         state: latest

  - block:
    - name: firewalld permits http service
      firewalld:
          service: http
          permanent: true
          state: enabled
          immediate: yes
  - block:
    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started
    - name: mariadb enabled and running
      service:
         name: mariadb
         enabled: true
         state: started
    - name: firewalld enabled and running
      service:
         name: firewalld
         enabled: true
         state: started
  - block:
    - name: get test php page
      get_url:
         url: "http://materials.example.com/grading/var/www/html/index.php"
         dest: /var/www/html/index.php
         mode: 0644
- name: test
  hosts: localhost
  tasks:
  - name: connect to internet web server
    uri:
       url: http://serverb.lab.example.com
       status_code: 200

