---
- name: Test reponse page web
  hosts: all
  tasks:         
    - name: verifie le status du site web
      win_uri:
        url: http://{{ ansible_host }}
        status_code: 200
      register: result
