---
- name: Test reponse page web
  hosts: all
  tasks:         
    - name: verifie le status du site web
      uri:
        url: http://18.212.148.66
        status_code: 200
      register: result
