---
- name: Test reponse page web
  hosts: all
    
  tasks:         
    - name: "verifie le status du site web
      uri:
        url: http://{{ ansible_host }}
        method: GET
        timeout: 30
        return_content: yes
      register: out
      
    - name: Print the msg
      debug:
        msg: "{{ out }}"
