---
- name: Mise à jour de RHEL 10
  hosts: all
  tasks: 
    - name: Upgrade all packages (dnf)
      yum:
        name: '*'
        state: latest
#        exclude: "{{ exclude_packages }}"
        update_only: true
      register: patchingresult
  
    - name: Check to see if we need a reboot
      command: dnf needs-restarting 
      register: result
      changed_when: result.rc == 1
      failed_when: result.rc > 1
      check_mode: false

    - name: Reboot Server if Necessary
      ansible.builtin.reboot:
      when: result.rc == 1
