---
- name: Update RHEL 2
  hosts: all 
  become: yes

  tasks: 
     - name: yum update 
       yum: name=* state=latest 
       register: result 
     
     - debug: 
         var: result 
     
     - name: install vim
       yum: name=vim state=present 
     
     - name: restart machine
       shell: sleep 2 && shutdown -r now "Ansible updates triggered"
       async: 1
       poll: 0
       ignore_errors: true

