---
- hosts: windows
  name: Mise à jour windows
  tasks:
    - name: Installer les mises à jour
      win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: '{{ reboot_server | default(true) }}'
