---
- name: Listen for events on a webhook
  hosts: all 
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: "Run job template"
      condition: event.payload.message == "Ansible is super cool"
      action:
        run_job_template:
          name: say-what
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
          retries: 1
          delay: 10
