---
- name: Events from Windows AD

  hosts: all
  sources:
   - ansible.eda.kafka:
       host: ec2-44-204-84-61.compute-1.amazonaws.com
       port: 9092
       topic: logs

  rules:
   - name: AD Account Change
     condition: event.body.winlog.event_id == "4722"
     action:
       run_job_template:
        organization: "Default"
        name: "Windows AD Events"

   - name: Security Event
     condition: event.body.message is search("Windows Defender Firewall")
     action:
       run_job_template:
         organization: "Default"
         name: "Amelioration ticket Windows AI"
